[connection]
endpoint = "http://pc:8882"
local_fallback = true

[sources]
include = ["src/**", "tests/**", "Cargo.toml", "Cargo.lock"]
exclude = []

[artifacts]
include = ["src/**", "Cargo.toml", "target/release/build-service", "target/release/build-cli"]
exclude = []

[request]
timeout_sec = 900

[request.env]
RUSTUP_HOME = "/opt/rust"
CARGO_HOME = "/opt/rust"

[workspace]
reuse = true
id = "build-service"
create = true
ttl_sec = 0

[output]
stdout_max_lines = 10
stderr_max_lines = 10
stdout_tail_lines = 10
stderr_tail_lines = 10
